description: Expires passwords for password cracked users using an Active Directory
  query integration instance.
id: Cymptom - Expire passwords for password cracked users
inputs: []
name: Cymptom - Expire passwords for password cracked users
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: db084095-7fdd-4d8a-8252-1ac3fd5d0300
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: db084095-7fdd-4d8a-8252-1ac3fd5d0300
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 65
        }
      }
  "3":
    defaultassigneecomplex:
      simple: admin
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      privileged: {}
      timeout: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This command returns users with cracked password
      id: 73a7c0df-636c-4c0c-8d8a-97e11dd2f0d4
      iscommand: true
      name: Cymptom - Get privileged users with cracked passwords
      script: '|||cymptom-get-users-with-cracked-passwords'
      type: regular
      version: -1
    taskid: 73a7c0df-636c-4c0c-8d8a-97e11dd2f0d4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 225
        }
      }
  "5":
    defaultassigneecomplex:
      simple: admin
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      base-dn: {}
      username:
        simple: ${Cymptom.CrackedUsers.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2
      description: Expires the password of an Active Directory user.
      id: c11a4f92-6498-4ee8-8e59-1f51912b0ccc
      iscommand: true
      name: AD - Expire passwords
      script: Active Directory Query v2|||ad-expire-password
      type: regular
      version: -1
    taskid: c11a4f92-6498-4ee8-8e59-1f51912b0ccc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 430,
        "width": 380,
        "x": 50,
        "y": 65
      }
    }
  }
fromversion: 5.0.0
tests:
- TestCymptomPlaybook
