description: Gets AD Information on cracked password users using an Active Directory
  query integration instance.
id: Cymptom - Get AD info on cracked password users
inputs: []
name: Cymptom - Get AD info on cracked password users
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d32544f-3c6f-4d6f-8d0a-734053543947
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 8d32544f-3c6f-4d6f-8d0a-734053543947
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "3":
    defaultassigneecomplex:
      simple: admin
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      privileged: {}
      timeout: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This command returns users with cracked password
      id: dc1c79f3-d2c1-4626-88ab-a1075d744ad9
      iscommand: true
      name: Cymptom-get-accounts
      script: '|||cymptom-get-users-with-cracked-passwords'
      type: regular
      version: -1
    taskid: dc1c79f3-d2c1-4626-88ab-a1075d744ad9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    defaultassigneecomplex:
      simple: admin
    id: "5"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      attributes: {}
      custom-field-data: {}
      custom-field-type: {}
      dn: {}
      email: {}
      limit: {}
      name: {}
      user-account-control-out: {}
      username:
        simple: ${Cymptom.CrackedUsers.Username}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Active Directory Query v2
      description: Retrieves detailed information about a user account. The user can
        be specified by name, email address, or as an Active Directory Distinguished
        Name (DN). If no filter is specified, all users are returned.
      id: 211b784a-9adb-42f5-89a9-f07efaf9e470
      iscommand: true
      name: AD-get-user
      script: Active Directory Query v2|||ad-get-user
      type: regular
      version: -1
    taskid: 211b784a-9adb-42f5-89a9-f07efaf9e470
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 5.0.0
tests:
- TestCymptomPlaybook
